decoder:
  vocab_size: 999
labels:
- _
- en
- er
- ch
- ei
- ie
- un
- st
- an
- ein
- der
- ich
- in
- ge
- sch
- au
- te
- de
- die
- und
- al
- den
- ar
- 'on'
- da
- gen
- be
- or
- se
- ten
- zu
- it
- hr
- ur
- es
- at
- ver
- ll
- ig
- ung
- ach
- ber
- ter
- das
- lich
- eine
- re
- le
- wi
- auf
- ne
- aus
- mit
- sie
- ist
- icht
- ben
- am
- im
- ier
- wei
- so
- fü
- ck
- sp
- rei
- ro
- ss
- von
- hn
- eit
- ste
- sich
- isch
- war
- des
- um
- tz
- el
- ra
- dem
- nicht
- ann
- men
- wir
- and
- wer
- ent
- als
- bei
- om
- wie
- is
- ol
- och
- auch
- her
- vor
- ft
- wa
- ion
- la
- gr
- he
- me
- ab
- ger
- ut
- über
- ze
- än
- il
- nach
- für
- ha
- kt
- wur
- lie
- all
- ff
- einen
- ind
- hl
- lei
- end
- iel
- hat
- tr
- dert
- einer
- ir
- ihr
- hun
- chen
- ssen
- hen
- we
- br
- urch
- unter
- hundert
- sa
- wo
- je
- ja
- werden
- nen
- mer
- zwei
- cht
- durch
- zig
- ik
- fr
- sen
- man
- pf
- wurde
- sten
- diese
- lo
- ungen
- lan
- wen
- aber
- ischen
- ien
- kom
- ern
- gt
- hal
- einem
- sel
- ort
- hin
- ür
- schen
- sind
- ser
- wird
- ma
- ige
- scha
- igen
- neun
- kann
- sta
- ück
- fa
- fe
- gel
- zehn
- gan
- ön
- lu
- tei
- noch
- mu
- sam
- geb
- ör
- daß
- pro
- kon
- ander
- hm
- son
- gesch
- du
- sein
- stell
- zur
- kl
- was
- är
- dr
- bl
- ün
- gte
- ken
- kr
- ische
- nur
- ing
- ot
- zum
- uch
- dar
- zeit
- drei
- acht
- ke
- oder
- ho
- na
- vier
- lichen
- ation
- ät
- ster
- ta
- jahr
- gew
- mehr
- ungs
- ihn
- em
- setz
- tet
- spr
- teil
- kön
- ul
- deut
- mal
- fün
- et
- fen
- fünf
- hatte
- hei
- llen
- pp
- bar
- iv
- land
- che
- doch
- zen
- gegen
- haben
- spiel
- pa
- äu
- schaft
- ba
- bis
- ßen
- dass
- liche
- for
- bt
- pr
- zei
- fol
- wenn
- taus
- gro
- wel
- wä
- ht
- di
- art
- tel
- wieder
- keit
- seine
- sehr
- ko
- tausend
- heit
- glei
- lle
- ihm
- gl
- det
- ner
- per
- führ
- alle
- gem
- fin
- iert
- str
- ute
- tra
- immer
- sech
- sei
- mir
- mö
- hau
- wan
- neu
- sit
- dann
- neunzehn
- dieser
- mar
- stand
- alt
- weiter
- ick
- bau
- fre
- mich
- dt
- ob
- wor
- us
- kam
- hier
- pt
- dern
- nu
- ffen
- waren
- pl
- soll
- tzt
- fall
- hmen
- fl
- schr
- ant
- sser
- del
- glich
- reich
- to
- gi
- wurden
- ßer
- äch
- kommen
- fahr
- vo
- bst
- ka
- ße
- qu
- herr
- ges
- hö
- ang
- hör
- dig
- eines
- stadt
- mü
- stra
- leben
- können
- fer
- viel
- zie
- erst
- tre
- ler
- nie
- bil
- bo
- gleich
- recht
- fä
- lin
- tes
- ga
- seiner
- ph
- imm
- eigen
- schon
- schie
- frei
- za
- ieren
- gar
- weise
- ihre
- ru
- atz
- mach
- sehen
- ange
- mei
- mann
- selbst
- ord
- gra
- reg
- iff
- habe
- ließ
- ill
- sagte
- halten
- mus
- chte
- ganz
- par
- nte
- zwan
- vie
- unkt
- deutsch
- iger
- gest
- ingen
- uns
- achtz
- grund
- verb
- nis
- nat
- fra
- vom
- ins
- po
- welt
- wür
- gibt
- zwi
- hne
- tete
- hand
- lang
- pol
- schu
- han
- zwanzig
- wohl
- ank
- fel
- geben
- su
- aum
- zwischen
- äl
- zahl
- aut
- seit
- inter
- län
- halb
- denn
- sse
- min
- weg
- unden
- net
- sammen
- eben
- 'null'
- bun
- schl
- stän
- zusammen
- arb
- komm
- menschen
- nun
- will
- kur
- tro
- lassen
- mittel
- flu
- zurück
- hol
- og
- inn
- esen
- möglich
- dien
- haus
- sprach
- the
- such
- beg
- cken
- zent
- gesetz
- sol
- ßig
- haupt
- keine
- att
- sechs
- voll
- öff
- do
- sy
- bur
- igkeit
- seinen
- betr
- ex
- anz
- itt
- sonder
- ierte
- bahn
- mein
- jetzt
- stehen
- blick
- ess
- mat
- pe
- ober
- sieben
- währ
- ßte
- konnte
- jedoch
- gs
- fort
- mo
- dort
- heute
- krie
- hän
- grö
- frau
- ersch
- si
- damit
- augen
- ug
- sicht
- ker
- dan
- fach
- besch
- ts
- weil
- ßt
- ende
- zeich
- nam
- arbei
- wissen
- äter
- ften
- ihnen
- dies
- gend
- zi
- eins
- öl
- nung
- zer
- wasser
- kte
- kehr
- best
- richt
- mä
- punkt
- ierung
- stu
- ald
- gut
- gemein
- ohne
- eur
- etwas
- ief
- ionen
- bin
- besonder
- ale
- arbeit
- wick
- während
- alles
- ausge
- seinem
- ca
- bel
- sicher
- mon
- fest
- sche
- aller
- dieses
- mals
- dabei
- sieb
- sü
- wahr
- ischer
- form
- nehmen
- denen
- mut
- prä
- fern
- bereit
- tern
- cher
- steht
- wirk
- bild
- tig
- undzwanzig
- ele
- nichts
- ater
- viele
- stellt
- star
- grün
- unde
- legen
- lag
- schul
- dreißig
- entwick
- tt
- diesem
- später
- euro
- oren
- bekann
- worden
- fu
- lieb
- auer
- iz
- ersten
- rich
- ihrer
- sto
- ihren
- hät
- lung
- anden
- kin
- spre
- uer
- schw
- beispiel
- alen
- unser
- groß
- wohn
- letz
- gehör
- einz
- häu
- fte
- frü
- meine
- anderen
- licher
- heim
- hiel
- gu
- jo
- bundes
- wirt
- los
- woll
- ätz
- glau
- gebie
- schei
- sah
- eln
- berei
- ähl
- amm
- sach
- erfol
- pu
- gehen
- häl
- ppen
- ding
- gab
- os
- as
- dich
- handel
- ieb
- müssen
- fil
- frie
- etwa
- neunzig
- vierzig
- ehn
- weit
- unge
- schließ
- uck
- lage
- licht
- äm
- neben
- außer
- werk
- verw
- enz
- burg
- kauf
- einige
- sondern
- achtzehn
- machen
- ommen
- jahre
- aten
- lange
- also
- deutschland
- lagen
- halt
- sagen
- fünfzig
- gef
- wort
- orden
- finden
- muss
- ad
- sollte
- beim
- hof
- verl
- hoch
- ku
- ität
- kar
- jahren
- inner
- cke
- andere
- einmal
- alten
- ging
- hinter
- schwer
- wirtschaft
- darauf
- fig
- einge
- mor
- trä
- ic
- erste
- nation
- diesen
- griff
- sor
- allen
- hren
- bi
- itz
- ow
- lau
- rück
- ppe
- stein
- fahren
- öffent
- schne
- berg
- ere
- ive
- hel
- führt
- tag
- zo
- zug
- schlu
- li
- hielt
- alter
- würde
- kein
- kel
- polit
- tem
- bereits
- reis
- hatten
- schiff
- statt
- beiden
- äft
- raum
- achtzig
- hlen
- liegt
- dor
- kre
- dazu
- zun
- sechzig
- co
- stellen
- trag
- wicht
- lö
- weiß
- klär
- har
- dessen
- sk
- angen
- itte
- einander
- spar
- gesam
- itten
- ktion
- deutschen
- schn
- plan
- könig
- kommt
- sitz
- rat
- vol
- verschie
- dir
- ju
- kü
- 'no'
- hü
- nahm
- tur
- lossen
- erz
- wegen
- schri
- blei
- gang
- ade
- nieder
- staat
- große
- einfach
- großen
- mi
- schrei
- ichte
- glie
- hält
- kun
- hätte
- spe
- kopf
- innen
- stre
- flü
- luft
- sst
- natür
- sowie
- kir
- tat
- ell
- findet
- igt
- geht
- kei
- wäre
- namen
- wollte
- gru
- uni
- oft
- genann
- treten
- mün
- stem
- got
- wert
- produ
- satz
- ieben
- falls
- iere
- macht
- lebens
- druck
- natur
- liegen
- bezeich
- undvierzig
- ütz
- seite
- pen
- brauch
- uten
- gewesen
- stellung
- ia
- tor
- essen
- unddreißig
- hme
- abge
- hil
- ks
- bald
- schein
- nt
- deck
- gesetzt
- jen
- zentr
- auen
- wach
- platz
- kra
- nä
- mensch
- wär
- west
- lauf
- chn
- zeu
- zw
- rom
- ssel
- rechts
- ble
- allem
- undneunzig
- ierten
- e
- n
- i
- r
- s
- t
- a
- d
- h
- u
- l
- c
- g
- m
- o
- b
- f
- w
- k
- z
- v
- p
- ü
- ä
- ö
- ß
- j
- y
- '-'
- x
- q
- ''''
- '2'
- ' '
preprocessor:
  frame_length: 25
  frame_shift: 10
  n_fft: 400
  n_mels: 80
  #normalize: true
  normalize: "per_feature"
  sample_rate: 16000
